#Apply BUSseq to the pancreas study.
rm(list=ls())
library(BUSseq)


######################
# Load Pancreas Data #
######################
# Working directory
# setwd("G:/scRNA/Journal/Github_reproduce/Human_Pancreas")

# Loading pancreas count data
load("./RawCountData/pancreas_countdata.RData")

#######################################
# Apply BUSseq to the Simulation Data #
#######################################
# the seed is a randomly sampled integer between 1 and 10,000 
seed.est <- 3982

# We've conduct the posterior infernce for the number of cell types K equal to  
# 3, 4, 5, 6, 7, 8 and select K = 12
K <- 12

# Conducting MCMC sampling
BUSseqfits_pancreas <- BUSseq_MCMC(ObservedData = PancreasCounts, n.celltypes = K,
                                     n.iterations = 8000, seed = seed.est,
                                     hyper_slab = 50, hyper_tau0 = c(2,0.01))

# # BIC values of other numbers of cell types are generated by the following codes
# # all seeds are randomly sampled between 1 and 10,000.
# # We strongly recommend to run the BUSseq_MCMC parallelly.
#
# BUSseqfits_pancreas_K6 <- BUSseq_MCMC(Data = PancreasCounts, n.celltypes = 6,
#                                      n.iterations = 8000, seed = 4158)
# BUSseqfits_pancreas_K7 <- BUSseq_MCMC(Data = PancreasCounts, n.celltypes = 7,
#                                       n.iterations = 8000, seed = 3313)
# BUSseqfits_pancreas_K8 <- BUSseq_MCMC(Data = PancreasCounts, n.celltypes = 8,
#                                       n.iterations = 8000, seed = 8413)
# BUSseqfits_pancreas_K9 <- BUSseq_MCMC(Data = PancreasCounts, n.celltypes = 9,
#                                       n.iterations = 8000, seed = 4107)
# BUSseqfits_pancreas_K10 <- BUSseq_MCMC(Data = PancreasCounts, n.celltypes = 10,
#                                       n.iterations = 8000, seed = 5015)
# BUSseqfits_pancreas_K11 <- BUSseq_MCMC(Data = PancreasCounts, n.celltypes = 11,
#                                       n.iterations = 8000, seed = 465)
# BUSseqfits_pancreas_K13 <- BUSseq_MCMC(Data = PancreasCounts, n.celltypes = 13,
#                                       n.iterations = 8000, seed = 8733)
# BUSseqfits_pancreas_K14 <- BUSseq_MCMC(Data = PancreasCounts, n.celltypes = 14,
#                                       n.iterations = 8000, seed = 3753)
# BUSseqfits_pancreas_K15 <- BUSseq_MCMC(Data = PancreasCounts, n.celltypes = 15,
#                                       n.iterations = 8000, seed = 1735)
# BUSseqfits_pancreas_K16 <- BUSseq_MCMC(Data = PancreasCounts, n.celltypes = 16,
#                                       n.iterations = 8000, seed = 1299)
# 
# BIC_values <- rep(NA,11)
# BIC_values[1] <- BIC_BUSseq(BUSseqfits_K6)
# BIC_values[2] <- BIC_BUSseq(BUSseqfits_K7)
# BIC_values[3] <- BIC_BUSseq(BUSseqfits_K8)
# BIC_values[4] <- BIC_BUSseq(BUSseqfits_K9)
# BIC_values[5] <- BIC_BUSseq(BUSseqfits_K10)
# BIC_values[6] <- BIC_BUSseq(BUSseqfits_K11)
# BIC_values[7] <- BIC_BUSseq(BUSseqfits)
# BIC_values[8] <- BIC_BUSseq(BUSseqfits_K13)
# BIC_values[9] <- BIC_BUSseq(BUSseqfits_K14)
# BIC_values[10] <- BIC_BUSseq(BUSseqfits_K15)
# BIC_values[11] <- BIC_BUSseq(BUSseqfits_K16)
# 
# names(BIC_values) <- paste0("K=",6:16)
# # As a result, the BIC values are
# # K=6      K=7      K=8      K=9      K=10     K=11     K=12     K=13     K=14     K=15     K=16
# # 72006473 72292608 72295139 71792528 71913120 71837285 71452177 71990214 71584400 71978947 72464600
# if(!dir.exists("Image")){
#   dir.create("Image")
# }
# if(!dir.exists("./Image/Other")){
#   dir.create("./Image/Other")
# }
# png("./Image/Other/BIC_values.png",width = 540, height = 720)
# par(mar = c(5.1,6.1,4.1,2.1))
# plot(6:16,BIC_values,xlab= "K",ylab = "BIC",type="n",cex.axis=3,cex.lab=3)
# points(6:16,BIC_values,type="b",pch=19,cex=3)
# dev.off()

#####################################
# Obtain the intrinsic gene indices #
#####################################
intrinsic_gene_indices <- intrinsic_genes_BUSseq(BUSseqfits_pancreas, fdr_threshold =  0.05)
intri_gene <- rownames(PancreasCounts[[1]])[intrinsic_gene_indices]
if(!dir.exists("Results")){
  dir.create("Results")
}

write.table(intri_gene,file="./Results/intrinsic_genes.txt",row.names = F,col.names = F,quote = F)

##################################
# Obain the cell type indicators #
##################################
w.est <- celltypes(BUSseqfits_pancreas)
w_BUSseq <- unlist(w.est) # change the list of cell type indicators to a vector


########################################
# Obtain the corrected read count data #
########################################
set.seed(12345)
B <- BUSseqfits_pancreas$n.batch
corrected_count_est <- corrected_read_counts(BUSseqfits_pancreas)
log_corrected_count_est <- NULL
for(b in 1:B){
  log_corrected_count_est <- cbind(log_corrected_count_est, log1p(corrected_count_est[[b]]))
}


# Store the workspace
if(!dir.exists("Workspace")){
  dir.create("Workspace")
}

save.image("./Workspace/BUSseq_workspace.RData")