#Apply BUSseq to the hematopoietic study.

rm(list=ls())
library(BUSseq)

###########################
# Load Hematopoietic Data #
###########################
# Working directory
# setwd("G:/scRNA/Journal/Github_reproduce/Mouse_Hematopoietic")

# Loading hematopoietic count data
load("./RawCountData/hemat_countdata.RData")
HematCounts <- list(GSE72857 = dataA2,
                    GSE81682 = dataF2)

##########################################
# Apply BUSseq to the Hematopoietic Data #
##########################################
# the seed is a randomly sampled integer between 1 and 10,000 
seed.est <- 4011

# We ran BUSseq for the number of cell types K equal to  
# 3, 4, 5, 6, 7, 8, 9 and 10, and select K = 7 according to BIC
K <- 7

# Conducting MCMC sampling
BUSseqfits_hemat <- BUSseq_MCMC(ObservedData = HematCounts, n.celltypes = K,
                                     n.iterations = 8000, seed = seed.est,
                                     hyper_slab = 50, hyper_tau0 = c(2,0.01))

# # BIC values of the other numbers of cell types are generated by the following codes
# # all seeds are randomly sampled between 1 and 10,000.
# # We strongly recommend running the BUSseq_MCMC in parallel.
# 
# BUSseqfits_hemat_K3 <- BUSseq_MCMC(Data = HematCounts, n.celltypes = 3,
#                                 n.iterations = 8000, seed = 6706,
#                                 hyper_slab = 50, hyper_tau0 = c(2,0.01))
# BUSseqfits_hemat_K4 <- BUSseq_MCMC(Data = HematCounts, n.celltypes = 4,
#                                 n.iterations = 8000, seed = 4693,
#                                 hyper_slab = 50, hyper_tau0 = c(2,0.01))
# BUSseqfits_hemat_K5 <- BUSseq_MCMC(Data = HematCounts, n.celltypes = 5,
#                                 n.iterations = 8000, seed = 4481,
#                                 hyper_slab = 50, hyper_tau0 = c(2,0.01))
# BUSseqfits_hemat_K6 <- BUSseq_MCMC(Data = HematCounts, n.celltypes = 6,
#                                 n.iterations = 8000, seed = 4078,
#                                 hyper_slab = 50, hyper_tau0 = c(2,0.01))
# BUSseqfits_hemat_K8 <- BUSseq_MCMC(Data = HematCounts, n.celltypes = 8,
#                                 n.iterations = 8000, seed = 1177,
#                                 hyper_slab = 50, hyper_tau0 = c(2,0.01))
# BUSseqfits_hemat_K9 <- BUSseq_MCMC(Data = HematCounts, n.celltypes = 9,
#                                 n.iterations = 8000, seed = 4654,
#                                 hyper_slab = 50, hyper_tau0 = c(2,0.01))
# BUSseqfits_hemat_K10 <- BUSseq_MCMC(Data = HematCounts, n.celltypes = 10,
#                                 n.iterations = 8000, seed = 7398,
#                                 hyper_slab = 50, hyper_tau0 = c(2,0.01))
# BIC_values <- rep(NA,8)
# BIC_values[1] <- BIC_BUSseq(BUSseqfits_hemat_K3)
# BIC_values[2] <- BIC_BUSseq(BUSseqfits_hemat_K4)
# BIC_values[3] <- BIC_BUSseq(BUSseqfits_hemat_K5)
# BIC_values[4] <- BIC_BUSseq(BUSseqfits_hemat_K6)
# BIC_values[5] <- BIC_BUSseq(BUSseqfits_hemat)
# BIC_values[6] <- BIC_BUSseq(BUSseqfits_hemat_K8)
# BIC_values[7] <- BIC_BUSseq(BUSseqfits_hemat_K9)
# BIC_values[8] <- BIC_BUSseq(BUSseqfits_hemat_K10)
# names(BIC_values) <- paste0("K=",3:10)
# # As a result, the BIC values are
# #  K=3      K=4      K=5      K=6      K=7      K=8       K=9       K=10
# # 48000531 47941792 47948555 47964609 47938554 48024762 48048079 48114358
# if(!dir.exists("Image")){
#   dir.create("Image")
# }
# if(!dir.exists("./Image/Other")){
#   dir.create("./Image/Other")
# }
# png("./Image/Other/BIC_values.png",width = 540, height = 720)
# par(mar = c(5.1,6.1,4.1,2.1))
# plot(3:10,BIC_values,xlab= "K",ylab = "BIC",type="n",cex.axis=3,cex.lab=3)
# points(3:10,BIC_values,type="b",pch=19,cex=3)
# dev.off()

#####################################
# Obtain the intrinsic gene indices #
#####################################
intrinsic_gene_indices <- intrinsic_genes_BUSseq(BUSseqfits_hemat, fdr_threshold =  0.05)


##################################
# Obtain the cell type indicators #
##################################
w.est <- celltypes(BUSseqfits_hemat)
w_BUSseq <- unlist(w.est) # change the list of cell type indicators to a vector


########################################
# Obtain the corrected read count data #
########################################
set.seed(12345)
B <- BUSseqfits_hemat$n.batch
corrected_count_est <- corrected_read_counts(BUSseqfits_hemat)
log_corrected_count_est <- NULL
for(b in 1:B){
  log_corrected_count_est <- cbind(log_corrected_count_est, log1p(corrected_count_est[[b]]))
}


# Store the workspace
if(!dir.exists("Workspace")){
  dir.create("Workspace")
}

save.image("./Workspace/BUSseq_workspace.RData")